version: '3'

services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: ./python3/Dockerfile
    working_dir: /src
    command: bash -c "uwsgi --socket :8001 --module app.wsgi:application --py-autoreload 1 --logto /var/log/wsgi/wsgi.log"
    volumes:
    - ./src/:/src/
    - ./logs/wsgi/:/var/log/wsgi
    - ./.vimrc:/root/.vimrc
    #- ./logs/supervisor/:/var/log/supervisor

    # expose: is just for linked services, and ports: is for the host OS
    expose:
      - "8001"
    #  - "8002"
    environment:
      PYTHONPATH: /src
    env_file:
      - .env
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static/:/src/static/
      - ./src/media/:/src/media/
      - ./logs/nginx/:/var/log/nginx/
      - ./.vimrc:/root/.vimrc
    depends_on:
      - python

  mysql:
    container_name: mysql
    build: ./mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} #optional
      MYSQL_USER: ${MYSQL_USER} #optional
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} #optional
      TZ: 'Asia/Tokyo'
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes" #optional
      # MYSQL_RANDOM_ROOT_PASSWORD: "yes" #optional
      # MYSQL_ONETIME_PASSWORD: "yes" #optional (MySQL 5.6 or above)
      # MYSQL_INITDB_SKIP_TZINFO: "" #optional
    expose:
      - "3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/conf/conf.d:/etc/mysql/conf.d
        #- ./logs/mysql/mysql/:/var/log/
        #- ./logs/mysql/mysqld/:/var/run/mysqld/
        - ./mysql/initdb.d:/docker-entrypoint-initdb.d
        - ./.vimrc:/root/.vimrc
    # To go inside this container:
    # docker exec -it mysql mysql -u polisadmin -p
    # P@ss_for_admin_005959
